config/routes.rb
Mygarage::Application.routes.draw do
  resources :jobs
  resources :vehicles do
    resources :jobs
  end
  
  root to: 'vehicles#index'

  

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  validates :name, presence: true
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job = Job.find(params[:vehicle_id])
  end

  # GET /jobs/new
  def new
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job = @vehicle.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to vehicle_job_path(@vehicle,@job), notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :odomoter, :date)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vehicle }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :year, :make, :model, :odometer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/jobs/_form.html.slim
= form_for [@vehicle,@job] do |f|
  - if @job.errors.any?
    #error_explanation
      h2 = "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      ul
        - @job.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :odomoter
    = f.text_field :odomoter
  .field
    = f.label :date
    = f.text_field :date
  .actions = f.submit 'Save'

app/views/jobs/edit.html.slim
h1 Editing job

== render 'form'

= link_to 'Show', @job
'|
= link_to 'Back', jobs_path

app/views/jobs/index.html.slim
h1 Listing jobs

table
  tr
    th Name
    th Odomoter
    th Date
    th
    th
    th

  - @jobs.each do |job|
    tr
      td = job.name
      td = job.odomoter
      td = job.date
      td = link_to 'Show', job
      td = link_to 'Edit', edit_job_path(job)
      td = link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Job', new_job_path

app/views/jobs/new.html.slim
h1 New job

== render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.slim
p#notice = notice

p
  strong Name:
  = @job.name
p
  strong Odomoter:
  = @job.odomoter
p
  strong Date:
  = @job.date

= link_to 'Edit', edit_vehicle_job_path(@vehicle, @job)
'|
= link_to 'Back', vehicle_path(@vehicle)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container row">

    <%= yield %>
</div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/vehicles/_form.html.slim
= form_for @vehicle do |f|
  - if @vehicle.errors.any?
    #error_explanation
      h2 = "#{pluralize(@vehicle.errors.count, "error")} prohibited this vehicle from being saved:"
      ul
        - @vehicle.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :make
    = f.text_field :make
  .field
    = f.label :model
    = f.text_field :model
  .field
    = f.label :odometer
    = f.text_field :odometer
  .actions = f.submit 'Save'

app/views/vehicles/edit.html.slim
h1 Editing vehicle

== render 'form'

= link_to 'Show', @vehicle
'|
= link_to 'Back', vehicles_path

app/views/vehicles/index.html.slim
h1 Vehicles

table
  tr
    th Name
    th Year
    th Make
    th Model
    th Odometer
    th
    th
    th

  - @vehicles.each do |vehicle|
    tr
      td = vehicle.name
      td = vehicle.year
      td = vehicle.make
      td = vehicle.model
      td = vehicle.odometer
      td = link_to 'Show', vehicle
      td = link_to 'Edit', edit_vehicle_path(vehicle)
      td = link_to 'Destroy', vehicle, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Vehicle', new_vehicle_path

app/views/vehicles/new.html.slim
h1 New vehicle

== render 'form'

= link_to 'Back', vehicles_path

app/views/vehicles/show.html.slim
p#notice = notice

h4
  = @vehicle.name
= @vehicle.year
' 
= @vehicle.make
' 
= @vehicle.model
' 
br
= @vehicle.odometer
'  miles (odometer reading)
 
table
  tr
    th Name
    th Odometer Target
    th Schedule

  - @vehicle.jobs.each do |job|
    tr
      td = link_to job.name, edit_vehicle_job_path(@vehicle, job)
      td = job.odomoter
      td = job.date
 

= link_to 'New Job', new_vehicle_job_path(@vehicle)
'|

= link_to 'Edit', edit_vehicle_path(@vehicle)
'|
= link_to 'Back', vehicles_path